### PR TITLE
replace librosa fbanks with own implementation supporting frequency w…

### PR DESCRIPTION
**Pull request by JanekEbb**
…arping (e.g. vtlp)

### CODE REVIEW

**Comment by jensheit** [comment]
Can we at this point remove librosa from our dependencies?

**Comment by TCord** [comment]
> Can we at this point remove librosa from our dependencies?

I think the only place librosa is also used at this moment is in case .m4a files are loaded. If we catch the exception with a  sufficiently explanatory error, removing librosa should be fine.

**Comment by boeddeker** [comment]
The `.m4a` files need `audioread` (dependency of `librosa`). So we could change the dependency `librosa` to `audioread`.

**Comment by TCord** [comment]
I think, the import of audioread already is lazy to have less dependencies. The file format .m4a is, after all, not a very common format. So removing librosa from dependencies without adding a new one should be the best option.

**Comment by boeddeker** [comment]
The dependency `librosa` is not a default dependency, it is included in the `all` dependency.
In the `all` dependency we should list all dependency.

**Pull request merged**
